### ISSUE TITLE
数据集网盘全失效了，能更新吗

### ISSUE THREAD

**Issue by BackT0TheFuture** [CVUsers/Fire-Detect-by-YoloV5#1]
谢谢

**Comment by CVUsers** [comment]
公众号里面有哦&nbsp; &nbsp;公众号&nbsp; DeepAI视界&nbsp; &nbsp;回复yolov5香烟 公众号二维码在博客里面有



---原始邮件---
发件人: "goodtogood"<notifications@github.com&gt;
发送时间: 2020年12月31日(周四) 中午1:00
收件人: "CVUsers/Fire-Detect-by-YoloV5"<Fire-Detect-by-YoloV5@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [CVUsers/Fire-Detect-by-YoloV5] 数据集网盘全失效了，能更新吗 (#1)




 
谢谢

**Comment by CVUsers** [comment]
链接：https://pan.baidu.com/s/1e_1Imzvlu94-0iAstdkuHA 提取码：deep 复制这段内容后打开百度网盘手机App，操作更方便哦 欢迎分享文章~欢迎进深度学习交流群------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月9日(星期四) 上午9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVUsers/Fire-Detect-by-YoloV5] 数据集网盘全失效了，能更新吗 (#1)
